language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tpargain/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tpargain/docker-react npm run test -- --coverage